# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
