# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20161127_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
